
export enum QuizzActionTypes {
  SAVE_QUIZ_DETAILS = 'SAVE_QUIZ_DETAILS',
  SAVE_ATTEMPT_ID = 'SAVE_ATTEMPT_ID',
  CACHE_QUESTION = 'CACHE_QUESTION',
  SELECT_QUESTION_OPTION = 'SELECT_QUESTION_OPTION',
  FINISH_ATTEMPT = 'FINISH_ATTEMPT'
};

export default QuizzActionTypes;