export const ERROR = "ERROR";
export const CONNECT = 'connect';
export const DISCONNECT = 'disconnect';
export const FETCH_QUIZ_DETAILS = 'FETCH_QUIZ_DETAILS';
export const UNAUTHORIZED = "UNAUTHORIZED";
export const RECEIVED_QUIZ_DETAILS = "RECEIVED_QUIZ_DETAILS";
export const START = "START";
export const FINISH = 'FINISH';
export const ATTEMPT_QUESTION = 'ATTEMPT_QUESTION';
export const FETCH_ATTEMPT_ID = 'FETCH_ATTEMPT_ID'
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const RECEIVED_QUESTION = 'RECEIVED_QUESTION';
export const FINISHED = "FINISHED";
export const NOT_FOUND='NOT_FOUND'